# Generated by Django 3.1.4 on 2021-02-04 06:07

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='titulo_texto_redes',
            field=models.CharField(default='Nosotros', max_length=255),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='color',
            field=colorfield.fields.ColorField(default='#97824B', max_length=18, verbose_name='Color principal'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='color2',
            field=colorfield.fields.ColorField(default='#005238', max_length=18, verbose_name='Color secundario'),
        ),
    ]
