# Generated by Django 3.1.4 on 2021-02-04 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookery', '0002_auto_20210204_0107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seccioncarta',
            options={'verbose_name': 'Sección carta', 'verbose_name_plural': '3 - Sección carta'},
        ),
        migrations.AlterModelOptions(
            name='seccioncontacto',
            options={'verbose_name': 'Sección contacto', 'verbose_name_plural': '5 - Sección contacto'},
        ),
        migrations.AlterModelOptions(
            name='seccionnosotros',
            options={'verbose_name': 'Sección nosotros', 'verbose_name_plural': '4 - Sección nosotros'},
        ),
        migrations.AlterModelOptions(
            name='seccionprincipal',
            options={'verbose_name': 'Sección principal', 'verbose_name_plural': '2 - Sección principal'},
        ),
        migrations.AddField(
            model_name='seccionnosotrosperks',
            name='seccion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cookery.seccionnosotros'),
            preserve_default=False,
        ),
    ]
