# Generated by Django 3.1.4 on 2021-02-06 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookery', '0003_auto_20210204_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccioncarta',
            name='imagen',
            field=models.ImageField(default='2.jpg', upload_to='cookery/secciones/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(help_text='Resolución recomendada 400x300', upload_to='productos/', verbose_name='Imagen'),
        ),
    ]
