# Generated by Django 3.1.4 on 2021-02-06 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookery', '0004_auto_20210205_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccioncontacto',
            name='imagen',
            field=models.ImageField(default='a.jpg', upload_to='cookery/secciones/'),
            preserve_default=False,
        ),
    ]
