# Generated by Django 3.1.4 on 2021-02-06 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookery', '0005_seccioncontacto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccioncontacto',
            name='mapa',
            field=models.TextField(blank=True, help_text='Opcional', null=True),
        ),
    ]
