# Generated by Django 3.1.4 on 2021-02-06 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookery', '0006_seccioncontacto_mapa'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeccionContactoPerks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('contenido', models.CharField(max_length=255, verbose_name='Contenido')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookery.seccioncontacto')),
            ],
            options={
                'verbose_name': 'Información de contacto',
                'verbose_name_plural': 'Informaciones de cotnacto',
            },
        ),
    ]
