# Generated by Django 3.1.4 on 2021-02-06 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookery', '0007_seccioncontactoperks'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccioncontactoperks',
            name='tipo',
            field=models.CharField(choices=[('tel', 'Teléfono'), ('mail', 'Email'), ('dir', 'Dirección'), ('whatsapp', 'WhatsApp')], default='tel', max_length=255, verbose_name='Tipo'),
            preserve_default=False,
        ),
    ]
