# Generated by Django 3.1.4 on 2021-02-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookery', '0009_auto_20210205_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destinatario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(blank=True, help_text='Opcional', max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Destinatario',
                'verbose_name_plural': '8 - Destinatarios',
            },
        ),
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=255, verbose_name='Teléfono o E-mail')),
                ('asunto', models.CharField(max_length=255)),
                ('mensaje', models.TextField()),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': '7 - Contactos',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Producto', 'verbose_name_plural': '6 - Productos'},
        ),
        migrations.AlterModelOptions(
            name='seccioncontactoperks',
            options={'verbose_name': 'Información de contacto', 'verbose_name_plural': 'Informaciones de contacto'},
        ),
    ]
