# Generated by Django 3.1.4 on 2021-02-07 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookery', '0010_auto_20210206_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='comentarios',
            field=models.BooleanField(default=True, verbose_name='Comentarios habilitados'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('contenido', models.TextField()),
                ('valido', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookery.product')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': '9 - Comentarios',
            },
        ),
    ]
