# Generated by Django 3.1.4 on 2021-02-07 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookery', '0012_comentario_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookery.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='valido',
            field=models.BooleanField(default=False, verbose_name='Válido'),
        ),
    ]
