# Generated by Django 3.1.4 on 2021-02-07 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookery', '0013_auto_20210206_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
