# Generated by Django 3.1.4 on 2021-02-08 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookery', '0016_auto_20210207_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='direccion',
            field=models.CharField(default='abdel', max_length=255, verbose_name='Dirección'),
            preserve_default=False,
        ),
    ]
