# Generated by Django 3.1.4 on 2021-02-08 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookery', '0017_pedido_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='contenido',
            field=models.TextField(blank=True, null=True),
        ),
    ]
