# Generated by Django 3.1.4 on 2021-02-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookery', '0018_pedido_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0, help_text='Opcional', verbose_name='Precio'),
        ),
    ]
