# Generated by Django 3.1.4 on 2021-02-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookery', '0020_remove_seccioncarta_subtitulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGodlango',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicializado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Configuración de ámbito global',
                'verbose_name_plural': '1 - Configuraciones de ámbito global',
            },
        ),
    ]
