# Generated by Django 3.1.4 on 2021-02-17 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookery', '0021_configuraciongodlango'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuraciongodlango',
            options={'verbose_name': 'Configuración de ámbito global', 'verbose_name_plural': '*  Configuraciones de ámbito global'},
        ),
        migrations.AddField(
            model_name='configuraciongodlango',
            name='has_previo',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Hash previo'),
        ),
    ]
