# Generated by Django 3.1.4 on 2021-02-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookery', '0022_auto_20210217_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despliegue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llave', models.CharField(max_length=500)),
                ('valor', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Despliegue',
                'verbose_name_plural': '**  Despliegues',
            },
        ),
    ]
