# Generated by Django 3.1.4 on 2021-02-17 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookery', '0023_despliegue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfiguracionGodlango',
        ),
        migrations.DeleteModel(
            name='Despliegue',
        ),
    ]
