# Generated by Django 3.1.4 on 2021-02-22 05:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookery', '0026_remove_pedido_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', ckeditor.fields.RichTextField(verbose_name='Horarios de servicio a domicilio')),
                ('zona', models.CharField(max_length=255)),
                ('precio', models.CharField(max_length=255, verbose_name='Teléfono')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': '11 - Zonas',
            },
        ),
    ]
