# Generated by Django 3.1.7 on 2021-03-06 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookery', '0029_configuracion_abierto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='abierto',
            field=models.BooleanField(default=True, verbose_name='Recibr pedidos'),
        ),
    ]
