# Generated by Django 3.1.7 on 2021-03-06 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookery', '0030_auto_20210305_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='msg',
            field=models.CharField(default='En estos momentos no estamos brindando servicio a domicilio, disculpe las molestias', max_length=255, verbose_name='Mensaje a mostrar cuando no se esté brindando servicio de entrega a domicilio'),
        ),
    ]
