# Generated by Django 3.0.2 on 2021-04-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookery', '0031_configuracion_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='calculado',
            field=models.BooleanField(default=False),
        ),
    ]
