# Generated by Django 3.2.3 on 2021-06-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookery', '0032_product_calculado'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='cart_like',
            field=models.CharField(default='Cuenta', help_text='Define cómo quieres llamar a la sección donde mostrarás la factura', max_length=255, verbose_name='Nombre de la Sección Detalles del Carrito'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuracion',
            name='carta_like',
            field=models.CharField(default='Carta', help_text='Define cómo quieres llamar a la sección donde mostrarás los productos', max_length=255, verbose_name='Nombre de la Sección Carta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuracion',
            name='moneda',
            field=models.CharField(default='U.S.D', max_length=255, verbose_name='Moneda a usar en la plataforma'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='porciento',
            field=models.FloatField(default=0, help_text='Porciento extra que se le agrega al precio de cada producto', verbose_name='Porcentaje de comisión'),
        ),
    ]
