# Generated by Django 3.2.3 on 2021-11-26 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookery', '0033_auto_20210621_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracion',
            name='abierto',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='cart_like',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='carta_like',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='comentarios',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='msg',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='telegram',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='texto_redes',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='titulo_texto_redes',
        ),
        migrations.AddField(
            model_name='configuracion',
            name='direccion',
            field=models.CharField(blank=True, help_text='Opcional', max_length=255, verbose_name='Dirección particular'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='tel',
            field=models.CharField(blank=True, help_text='Opcional', max_length=255, verbose_name='Telefono fijo del establecimiento'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='logo',
            field=models.ImageField(upload_to='cfg/', verbose_name='Imagen principal'),
        ),
    ]
