# Generated by Django 3.2.3 on 2021-11-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookery', '0034_auto_20211125_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galeriaproducto',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='productoperks',
            name='producto',
        ),
        migrations.DeleteModel(
            name='SeccionCarta',
        ),
        migrations.RemoveField(
            model_name='seccioncontactoperks',
            name='seccion',
        ),
        migrations.RemoveField(
            model_name='seccionnosotrosperks',
            name='seccion',
        ),
        migrations.DeleteModel(
            name='SeccionPrincipal',
        ),
        migrations.RemoveField(
            model_name='product',
            name='especial',
        ),
        migrations.AlterField(
            model_name='product',
            name='contenido',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.DeleteModel(
            name='GaleriaProducto',
        ),
        migrations.DeleteModel(
            name='ProductoPerks',
        ),
        migrations.DeleteModel(
            name='SeccionContacto',
        ),
        migrations.DeleteModel(
            name='SeccionContactoPerks',
        ),
        migrations.DeleteModel(
            name='SeccionNosotros',
        ),
        migrations.DeleteModel(
            name='SeccionNosotrosPerks',
        ),
    ]
