# Generated by Django 3.2.3 on 2021-11-26 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookery', '0035_auto_20211126_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cfg',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cookery.configuracion'),
        ),
    ]
