# Generated by Django 3.2.3 on 2021-11-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookery', '0036_product_cfg'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='qr_img',
            field=models.ImageField(default='asdasd', upload_to='', verbose_name='QR'),
            preserve_default=False,
        ),
    ]
