# Generated by Django 3.2.3 on 2021-11-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookery', '0037_configuracion_qr_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='qr_img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='QR'),
        ),
    ]
