# Generated by Django 3.2.3 on 2021-11-27 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookery', '0038_alter_configuracion_qr_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='product',
        ),
        migrations.DeleteModel(
            name='Destinatario',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='Reservacion',
        ),
        migrations.RemoveField(
            model_name='zonaperk',
            name='fk',
        ),
        migrations.AlterModelOptions(
            name='zona',
            options={'verbose_name': 'Especificaciones del servicio a domicilio', 'verbose_name_plural': 'Especificaciones del servicio a domicilio'},
        ),
        migrations.AddField(
            model_name='zona',
            name='cfg',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cookery.configuracion'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='ZonaPerk',
        ),
    ]
