# Generated by Django 3.2.3 on 2021-11-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookery', '0039_auto_20211127_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='zona',
            name='dia',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zona',
            name='horario',
            field=models.CharField(max_length=255),
        ),
    ]
