# Generated by Django 3.2.3 on 2021-11-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookery', '0041_auto_20211130_0732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ('orden',), 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AddField(
            model_name='categoria',
            name='orden',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
