# Generated by Django 3.2.3 on 2021-11-30 12:54

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookery', '0043_configuracion_recibir_pedidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='color3',
            field=colorfield.fields.ColorField(default='#005238', max_length=18, verbose_name='Color de fondo'),
        ),
    ]
