# Generated by Django 3.2.3 on 2021-11-30 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cookery', '0044_configuracion_color3'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='regenerar',
            field=models.BooleanField(default=False, verbose_name='Volver a generar qr'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='usuario',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='qr_img',
            field=models.CharField(default='/qr/1.png', max_length=900),
            preserve_default=False,
        ),
    ]
