# Generated by Django 3.1.4 on 2021-02-17 22:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godjango', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='despliegue',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 17, 17, 13, 54, 473445)),
        ),
    ]
