# Generated by Django 3.1.4 on 2021-02-17 22:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godjango', '0002_despliegue_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despliegue',
            name='fecha',
        ),
        migrations.AddField(
            model_name='despliegue',
            name='hora',
            field=models.TimeField(default=datetime.datetime(2021, 2, 17, 17, 15, 42, 22724)),
        ),
    ]
