# Generated by Django 3.1.4 on 2021-02-17 23:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godjango', '0003_auto_20210217_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despliegue',
            name='hora',
            field=models.TimeField(default=datetime.datetime(2021, 2, 17, 18, 52, 31, 933829)),
        ),
    ]
