# Generated by Django 3.1.4 on 2021-02-18 02:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godjango', '0005_auto_20210217_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despliegue',
            name='hora',
            field=models.TimeField(default=datetime.datetime(2021, 2, 17, 21, 29, 28, 741362)),
        ),
    ]
