# Generated by Django 3.1.4 on 2021-02-22 05:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godjango', '0006_auto_20210217_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despliegue',
            name='hora',
            field=models.TimeField(default=datetime.datetime(2021, 2, 22, 0, 26, 15, 619106)),
        ),
    ]
