# Generated by Django 3.1.7 on 2021-03-06 03:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godjango', '0009_auto_20210305_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despliegue',
            name='hora',
            field=models.TimeField(default=datetime.datetime(2021, 3, 5, 22, 18, 40, 202910)),
        ),
    ]
