# Generated by Django 3.0.2 on 2021-03-20 02:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godjango', '0011_auto_20210305_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciongodlango',
            name='porciento',
            field=models.FloatField(default=0, help_text='Porciento extra que se le agrega al precio de cada producto', verbose_name='Porcentaje de comisión'),
        ),
        migrations.AlterField(
            model_name='despliegue',
            name='hora',
            field=models.TimeField(default=datetime.datetime(2021, 3, 19, 22, 30, 8, 946045)),
        ),
    ]
