# Generated by Django 3.0.2 on 2021-03-28 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godjango', '0012_auto_20210319_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despliegue',
            name='hora',
            field=models.TimeField(default=datetime.datetime(2021, 3, 28, 10, 51, 32, 351978)),
        ),
    ]
