# Generated by Django 3.0.2 on 2021-04-07 05:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godjango', '0013_auto_20210328_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despliegue',
            name='hora',
            field=models.TimeField(default=datetime.datetime(2021, 4, 7, 1, 22, 19, 445408)),
        ),
    ]
