# Generated by Django 3.2.3 on 2021-06-21 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godjango', '0014_auto_20210407_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despliegue',
            name='hora',
            field=models.TimeField(default=datetime.datetime(2021, 6, 21, 11, 1, 43, 987599)),
        ),
    ]
