# Generated by Django 3.2.3 on 2021-11-26 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godjango', '0017_alter_despliegue_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despliegue',
            name='hora',
            field=models.TimeField(default=datetime.datetime(2021, 11, 26, 7, 1, 30, 371618)),
        ),
    ]
