# Generated by Django 3.2.3 on 2021-11-27 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godjango', '0018_alter_despliegue_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despliegue',
            name='hora',
            field=models.TimeField(default=datetime.datetime(2021, 11, 27, 12, 1, 16, 304141)),
        ),
    ]
