# Generated by Django 3.2.3 on 2021-11-27 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godjango', '0019_alter_despliegue_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciongodlango',
            name='url',
            field=models.CharField(default='asdasd', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='despliegue',
            name='hora',
            field=models.TimeField(default=datetime.datetime(2021, 11, 27, 12, 6, 18, 335431)),
        ),
    ]
