# Generated by Django 3.2.3 on 2021-11-27 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godjango', '0020_auto_20211127_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despliegue',
            name='hora',
            field=models.TimeField(default=datetime.datetime(2021, 11, 27, 12, 8, 15, 505757)),
        ),
    ]
