# Generated by Django 3.2.3 on 2021-11-30 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('godjango', '0026_alter_despliegue_hora'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Despliegue',
        ),
        migrations.RemoveField(
            model_name='configuraciongodlango',
            name='has_previo',
        ),
        migrations.RemoveField(
            model_name='configuraciongodlango',
            name='inicializado',
        ),
    ]
